package io.github.alexistrejo11.pimienta.module.inventory.core.application.usecase;
import io.github.alexistrejo11.pimienta.module.inventory.core.application.command.InventoryCountCommands; import io.github.alexistrejo11.pimienta.module.inventory.core.domain.*; import io.github.alexistrejo11.pimienta.module.inventory.core.domain.InventoryMovement.InventoryMovementType; import io.github.alexistrejo11.pimienta.module.inventory.core.domain.InventoryTransaction.TransactionType; import io.github.alexistrejo11.pimienta.module.inventory.core.port.input.InventoryCountUseCases; import io.github.alexistrejo11.pimienta.module.inventory.core.port.output.*; import java.math.BigDecimal; import java.time.LocalDateTime; import java.util.concurrent.ThreadLocalRandom; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
@Service public class InventoryCountUseCasesImpl implements InventoryCountUseCases {
 private final InventoryCountRepository counts; private final InventoryRepository inventory; private final ItemRepository items; private final InventoryTransactionRepository transactions; private final InventoryMovementRepository movements; private final StorageLocationRepository locations;
 public InventoryCountUseCasesImpl(InventoryCountRepository c,InventoryRepository i,ItemRepository it,InventoryTransactionRepository t,InventoryMovementRepository m,StorageLocationRepository l){counts=c;inventory=i;items=it;transactions=t;movements=m;locations=l;}
 public InventoryCountSession get(long id){return counts.findById(id).orElseThrow(()->new IllegalArgumentException("Inventory count session not found: "+id));}
 @Transactional public InventoryCountSession open(InventoryCountCommands.Open c){if((!"FULL".equals(c.type())&&!"PARTIAL".equals(c.type()))||(c.itemIds()==null&&"PARTIAL".equals(c.type())))throw new IllegalArgumentException("Invalid count type or item scope");if(counts.existsActiveByLocationId(c.locationId()))throw new IllegalStateException("Location already has an active count");locations.findById(c.locationId()).orElseThrow(()->new IllegalArgumentException("Location not found"));var s=InventoryCountSession.open(c.locationId(),InventoryCountSession.CountType.valueOf(c.type()),c.createdById());var ids="FULL".equals(c.type())?inventory.findByLocationId(c.locationId()).stream().map(i->i.getItem().getId()).toList():c.itemIds().stream().distinct().toList();for(long itemId:ids){items.findById(itemId).orElseThrow(()->new IllegalArgumentException("Item not found: "+itemId));int expected=inventory.findByItemIdAndLocationId(itemId,c.locationId()).map(Inventory::getAvailableQuantity).orElse(0);s.addResponse(new InventoryCountResponse(itemId,expected));}return counts.save(s);}
 @Transactional public InventoryCountSession respond(long id,InventoryCountCommands.Response c){var s=get(id);if(s.getStatus()!=InventoryCountSession.Status.DRAFT)throw new IllegalStateException("Count is not a draft");var r=s.getResponses().stream().filter(x->x.getItemId().equals(c.itemId())).findFirst().orElseThrow(()->new IllegalArgumentException("Item is not in count scope"));if(c.countedQuantity()<0)throw new IllegalArgumentException("Counted quantity cannot be negative");r.setCountedQuantity(c.countedQuantity());r.setCountedAt(LocalDateTime.now());return counts.save(s);}
 @Transactional public InventoryCountSession submit(long id,long user){var s=get(id);if(s.getStatus()!=InventoryCountSession.Status.DRAFT)throw new IllegalStateException("Count is not a draft");if(s.getResponses().stream().anyMatch(r->r.getCountedQuantity()==null))throw new IllegalStateException("All count responses are required");s.getResponses().forEach(r->r.setVariance(r.getCountedQuantity()-r.getExpectedQuantity()));s.setStatus(InventoryCountSession.Status.SUBMITTED);s.setSubmittedById(user);s.setSubmittedAt(LocalDateTime.now());return counts.save(s);}
  @Transactional public InventoryCountSession approve(long id,long user){var s=get(id);if(s.getStatus()==InventoryCountSession.Status.APPROVED)return s;if(s.getStatus()!=InventoryCountSession.Status.SUBMITTED)throw new IllegalStateException("Count is not submitted");if(user==s.getCreatedById())throw new IllegalStateException("Creator cannot approve own count");var tx=InventoryTransaction.open("COUNT-"+System.currentTimeMillis()+ThreadLocalRandom.current().nextInt(1000,9999),TransactionType.PHYSICAL_COUNT,null,"Physical inventory count "+id,user);tx=transactions.save(tx);for(var r:s.getResponses()){if(r.getVariance()==0)continue;var inv=inventory.findByItemIdAndLocationId(r.getItemId(),s.getLocationId()).orElseThrow(()->new IllegalArgumentException("Inventory row not found"));int current=inv.getAvailableQuantity();int target=current+r.getVariance();if(target<0)throw new IllegalStateException("Count variance would make stock negative");if(r.getVariance()>0)inv.addStock(r.getVariance());else inv.removeStock(-r.getVariance());inventory.save(inv);var m=r.getVariance()>0?InventoryMovement.recordEntry(inv.getItem(),inv.getLocation(),r.getVariance(),BigDecimal.ZERO,InventoryMovementType.ADJUSTMENT_PLUS,"COUNT-"+id,"Physical count variance",user,inv.getAvailableQuantity()):InventoryMovement.recordExit(inv.getItem(),inv.getLocation(),-r.getVariance(),BigDecimal.ZERO,InventoryMovementType.ADJUSTMENT_MINUS,"COUNT-"+id,"Physical count variance",user,inv.getAvailableQuantity());m.setTransactionId(tx.getId());movements.save(m);}tx.complete();transactions.save(tx);s.setStatus(InventoryCountSession.Status.APPROVED);s.setApprovedById(user);s.setApprovedAt(LocalDateTime.now());return counts.save(s);}
 @Transactional public void cancel(long id){var s=get(id);if(s.getStatus()==InventoryCountSession.Status.APPROVED)throw new IllegalStateException("Approved count cannot be cancelled");s.setStatus(InventoryCountSession.Status.CANCELLED);s.setCancelledAt(LocalDateTime.now());counts.save(s);}
}
