package io.github.alexistrejo11.pimienta.shared.exception;

public enum ErrorCode {
  RESOURCE_NOT_FOUND("RESOURCE_NOT_FOUND"),
  HEADQUARTER_NOT_FOUND("HEADQUARTER_NOT_FOUND"),

  VALIDATION_FAILED("VALIDATION_FAILED"),
  CONSTRAINT_VIOLATION("CONSTRAINT_VIOLATION"),
  INVALID_ARGUMENT("INVALID_ARGUMENT"),
  MALFORMED_PAYLOAD("MALFORMED_PAYLOAD"),
  MISSING_PARAMETER("MISSING_PARAMETER"),
  TYPE_MISMATCH("TYPE_MISMATCH"),

  CONFLICT("CONFLICT"),
  UNAUTHORIZED("UNAUTHORIZED"),
  FORBIDDEN("FORBIDDEN"),
  AUTHENTICATION_FAILED("AUTHENTICATION_FAILED"),

  USER_NOT_FOUND("USER_NOT_FOUND"),
  EMPLOYEE_NOT_FOUND("EMPLOYEE_NOT_FOUND"),
  ATTENDANCE_NOT_FOUND("ATTENDANCE_NOT_FOUND"),
  ATTENDANCE_ALREADY_OPEN("ATTENDANCE_ALREADY_OPEN"),
  ATTENDANCE_NOT_OPEN_FOR_CHECKOUT("ATTENDANCE_NOT_OPEN_FOR_CHECKOUT"),
  TASK_NOT_FOUND("TASK_NOT_FOUND"),
  TASK_CHECKLIST_ITEM_NOT_FOUND("TASK_CHECKLIST_ITEM_NOT_FOUND"),

  OPPORTUNITY_NOT_FOUND("OPPORTUNITY_NOT_FOUND"),
  PROJECT_NOT_FOUND("PROJECT_NOT_FOUND"),
  PROJECT_MILESTONE_NOT_FOUND("PROJECT_MILESTONE_NOT_FOUND"),

  CONTRACT_NOT_FOUND("CONTRACT_NOT_FOUND"),

  ITEM_NOT_FOUND("ITEM_NOT_FOUND"),
  ITEM_SKU_ALREADY_EXISTS("ITEM_SKU_ALREADY_EXISTS"),
  ITEM_BARCODE_ALREADY_EXISTS("ITEM_BARCODE_ALREADY_EXISTS"),
  STORAGE_LOCATION_NOT_FOUND("STORAGE_LOCATION_NOT_FOUND"),
  STORAGE_LOCATION_NOT_EMPTY("STORAGE_LOCATION_NOT_EMPTY"),
  POS_LOCATION_NOT_FOUND("POS_LOCATION_NOT_FOUND"),
  INVENTORY_NOT_FOUND("INVENTORY_NOT_FOUND"),
  INVENTORY_ALREADY_EXISTS("INVENTORY_ALREADY_EXISTS"),
  INVENTORY_MOVEMENT_NOT_FOUND("INVENTORY_MOVEMENT_NOT_FOUND"),
  INVENTORY_TRANSACTION_NOT_FOUND("INVENTORY_TRANSACTION_NOT_FOUND"),
  INVENTORY_TRANSACTION_INVALID_STATE("INVENTORY_TRANSACTION_INVALID_STATE"),
  HEADQUARTER_ITEM_NOT_FOUND("HEADQUARTER_ITEM_NOT_FOUND"),
  HEADQUARTER_POS_SETTINGS_NOT_FOUND("HEADQUARTER_POS_SETTINGS_NOT_FOUND"),
  POS_DEVICE_NOT_FOUND("POS_DEVICE_NOT_FOUND"),
  POS_DEVICE_REVOKED("POS_DEVICE_REVOKED"),
  POS_DEVICE_ALREADY_ENROLLED("POS_DEVICE_ALREADY_ENROLLED"),
  POS_ENROLLMENT_CODE_INVALID("POS_ENROLLMENT_CODE_INVALID"),
  POS_ENROLLMENT_CODE_EXPIRED("POS_ENROLLMENT_CODE_EXPIRED"),
  POS_ENROLLMENT_CODE_CONSUMED("POS_ENROLLMENT_CODE_CONSUMED"),
  POS_OPERATOR_NOT_FOUND("POS_OPERATOR_NOT_FOUND"),
  POS_SYNC_CURSOR_INVALID("POS_SYNC_CURSOR_INVALID"),
  POS_SYNC_INCIDENT_NOT_FOUND("POS_SYNC_INCIDENT_NOT_FOUND"),
  POS_SYNC_INCIDENT_ALREADY_ACCEPTED("POS_SYNC_INCIDENT_ALREADY_ACCEPTED"),
  POS_APK_NOT_FOUND("POS_APK_NOT_FOUND"),
  EMAIL_ALREADY_EXISTS("EMAIL_ALREADY_EXISTS"),
  PHONE_ALREADY_EXISTS("PHONE_ALREADY_EXISTS"),
  USER_BANNED("USER_BANNED"),
  ACCOUNT_PENDING_APPROVAL("ACCOUNT_PENDING_APPROVAL"),
  INVALID_REFRESH_TOKEN("INVALID_REFRESH_TOKEN"),
  INVALID_DEVICE_REFRESH_TOKEN("INVALID_DEVICE_REFRESH_TOKEN"),

  UNSUPPORTED_MEDIA_TYPE("UNSUPPORTED_MEDIA_TYPE"),
  METHOD_NOT_ALLOWED("METHOD_NOT_ALLOWED"),

  OBJECT_STORAGE_ERROR("OBJECT_STORAGE_ERROR"),

  INTERNAL_ERROR("INTERNAL_ERROR");

  private final String code;

  ErrorCode(String code) {
    this.code = code;
  }

  public String code() {
    return code;
  }
}
