package io.github.alexistrejo11.pimienta.shared.exception;

public enum ErrorCode {
  RESOURCE_NOT_FOUND("RESOURCE_NOT_FOUND"),
  HEADQUARTER_NOT_FOUND("HEADQUARTER_NOT_FOUND"),

  VALIDATION_FAILED("VALIDATION_FAILED"),
  CONSTRAINT_VIOLATION("CONSTRAINT_VIOLATION"),
  INVALID_ARGUMENT("INVALID_ARGUMENT"),
  MALFORMED_PAYLOAD("MALFORMED_PAYLOAD"),
  MISSING_PARAMETER("MISSING_PARAMETER"),
  TYPE_MISMATCH("TYPE_MISMATCH"),

  CONFLICT("CONFLICT"),
  UNAUTHORIZED("UNAUTHORIZED"),
  FORBIDDEN("FORBIDDEN"),
  AUTHENTICATION_FAILED("AUTHENTICATION_FAILED"),

  USER_NOT_FOUND("USER_NOT_FOUND"),
  EMPLOYEE_NOT_FOUND("EMPLOYEE_NOT_FOUND"),
  EMAIL_ALREADY_EXISTS("EMAIL_ALREADY_EXISTS"),
  USER_BANNED("USER_BANNED"),
  INVALID_REFRESH_TOKEN("INVALID_REFRESH_TOKEN"),

  UNSUPPORTED_MEDIA_TYPE("UNSUPPORTED_MEDIA_TYPE"),
  METHOD_NOT_ALLOWED("METHOD_NOT_ALLOWED"),

  INTERNAL_ERROR("INTERNAL_ERROR");

  private final String code;

  ErrorCode(String code) {
    this.code = code;
  }

  public String code() {
    return code;
  }
}
