package io.github.alexistrejo11.pimienta.module.inventory.infrastructure.adapter.inbound.web;
import static io.github.alexistrejo11.pimienta.shared.web.ApiPaths.BASE;
import io.github.alexistrejo11.pimienta.config.security.JwtAuthenticationContext; import io.github.alexistrejo11.pimienta.module.account.user.core.application.HeadquarterAccessService; import io.github.alexistrejo11.pimienta.module.inventory.core.application.command.InventoryCountCommands; import io.github.alexistrejo11.pimienta.module.inventory.core.domain.InventoryCountSession; import io.github.alexistrejo11.pimienta.module.inventory.core.port.input.*; import io.github.alexistrejo11.pimienta.module.inventory.infrastructure.adapter.inbound.web.dto.request.*; import io.github.alexistrejo11.pimienta.module.inventory.infrastructure.adapter.inbound.web.dto.response.*; import io.github.alexistrejo11.pimienta.module.inventory.core.port.input.StorageLocationManagementUseCases; import jakarta.validation.Valid; import org.springframework.security.access.AccessDeniedException; import org.springframework.security.core.annotation.AuthenticationPrincipal; import org.springframework.web.bind.annotation.*;
@RestController @RequestMapping(BASE+"/inventory/count-sessions") public class InventoryCountController {
 private final InventoryCountUseCases useCases; private final StorageLocationManagementUseCases locations; private final HeadquarterAccessService access;
 public InventoryCountController(InventoryCountUseCases u,StorageLocationManagementUseCases l,HeadquarterAccessService a){useCases=u;locations=l;access=a;}
 @PostMapping public InventoryCountSessionResponse open(@AuthenticationPrincipal JwtAuthenticationContext p,@Valid @RequestBody OpenInventoryCountRequest r){check(p,r.locationId());return dto(useCases.open(new InventoryCountCommands.Open(r.locationId(),r.type(),r.itemIds(),p.userId())),false);}
 @GetMapping("/{id}") public InventoryCountSessionResponse get(@AuthenticationPrincipal JwtAuthenticationContext p,@PathVariable long id){var s=useCases.get(id);check(p,s.getLocationId());return dto(s,s.getStatus()==InventoryCountSession.Status.APPROVED);}
 @PostMapping("/{id}/responses") public InventoryCountSessionResponse respond(@AuthenticationPrincipal JwtAuthenticationContext p,@PathVariable long id,@Valid @RequestBody InventoryCountResponseRequest r){var s=useCases.get(id);check(p,s.getLocationId());return dto(useCases.respond(id,new InventoryCountCommands.Response(r.itemId(),r.countedQuantity())),false);}
 @PostMapping("/{id}/submit") public InventoryCountSessionResponse submit(@AuthenticationPrincipal JwtAuthenticationContext p,@PathVariable long id){var s=useCases.get(id);check(p,s.getLocationId());return dto(useCases.submit(id,p.userId()),false);}
  @PostMapping("/{id}/approve") public InventoryCountSessionResponse approve(@AuthenticationPrincipal JwtAuthenticationContext p,@PathVariable long id){var s=useCases.get(id);check(p,s.getLocationId());if(!p.roles().contains("ADMIN")&&!p.roles().contains("MANAGER"))throw new AccessDeniedException("Only administrators and managers may approve counts");return dto(useCases.approve(id,p.userId()),true);}
 @PostMapping("/{id}/cancel") public void cancel(@AuthenticationPrincipal JwtAuthenticationContext p,@PathVariable long id){var s=useCases.get(id);check(p,s.getLocationId());useCases.cancel(id);}
 private void check(JwtAuthenticationContext p,long locationId){access.requireOwnedLocation(p,locations.getById(locationId).getHeadquarterId());}
 private InventoryCountSessionResponse dto(InventoryCountSession s,boolean reveal){return new InventoryCountSessionResponse(s.getId(),s.getLocationId(),s.getCountType(),s.getStatus(),s.getCreatedById(),s.getSubmittedById(),s.getApprovedById(),s.getCreatedAt(),s.getSubmittedAt(),s.getApprovedAt(),s.getCancelledAt(),s.getResponses().stream().map(r->new InventoryCountResponseDto(r.getItemId(),reveal?r.getExpectedQuantity():null,r.getCountedQuantity(),reveal?r.getVariance():null)).toList());}
}
