spring:
  application:
    name: pimienta
  # PostgreSQL
  datasource:
    url: jdbc:postgresql://localhost:5432/pimienta_alimentos
    username: pimienta_dba
    password: pimienta_dba
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  # Redis
  data:
    redis:
      host: localhost
      port: 6379
  # Server
  server:
    port: 8080
  # Logging
  logging:
    level:
      org.springframework.web: DEBUG

pimienta:
  security:
    jwt:
      secret: "change-me-use-at-least-256-bits-for-hs256-secret-key-pimienta"
      access-token-ttl-minutes: 15
      refresh-token-ttl-days: 7
