name: pimienta-alimentos

services:
  web:
    image: pimienta-web:local
    build:
      context: .
    env_file:
      - .env
    ports:
      - '${PORT:-4000}:4000'
    environment:
      PORT: '4000'
      API_BASE_URL: ${API_BASE_URL}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS}
    restart: unless-stopped
    networks:
      - pimienta-net

networks:
  pimienta-net:
    external: true
